"""init

Revision ID: 286cd6eaf04a
Revises: 50dd06a7258f
Create Date: 2024-03-23 06:54:37.570508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286cd6eaf04a'
down_revision: Union[str, None] = '50dd06a7258f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'data')
    # ### end Alembic commands ###
