"""init

Revision ID: 760909d85a3a
Revises: 65f61a8542fb
Create Date: 2024-03-24 04:40:05.786017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760909d85a3a'
down_revision: Union[str, None] = '65f61a8542fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)
    # ### end Alembic commands ###
