"""init

Revision ID: f9d80b31b281
Revises: 3b618d5d0d05
Create Date: 2024-03-29 23:41:21.280886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d80b31b281'
down_revision: Union[str, None] = '3b618d5d0d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
